version: "3.7"

services:

  ### Application ###
  JexxaTemplate: # TODO: Change <ProjectName> (CamelCase)
    image: ghcr.io/jexxa-projects/jexxatemplate:latest # TODO: change image location ghcr.io/<your profile>/<projectname>:latest
    ports:
      - "7508:7500" # TODO: Adjust HTTP Port "<free HTTP-Port>:7500"
    depends_on:
      - ActiveMQ
      - Postgres

    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider 'http://localhost:7500/BoundedContext/isRunning/'"]
      interval: 10s
      timeout: 10s
      retries: 3

    deploy:   # configure zero downtime deployment
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback

      rollback_config:
        parallelism: 1
        order: start-first

      restart_policy:
        condition: on-failure

  ### Infrastructure ###

  ActiveMQ:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      AMQ_EXTRA_ARGS: --relax-jolokia

  Postgres:
    image: postgres:latest
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
